### ISSUE TITLE
Feedback on tutorial 

### ISSUE THREAD

**Issue by orla03** [EdDataScienceEES/tutorial-shaistilman#1]
This is a really good tutorial, I love the layout and you have very good descriptions, it is very informative at each step! The tables are very clear, love these!

A few considerations to change:
3.1 - maybe change second sentence to “It is one of”, spelling of “remember” (3rd line)
- You probably don’t need to reintroduce the data each time, when it is introduced at the start.
- When creating the model I would maybe add something like “we are trying to see how military coups change depending on a number of factors …” as otherwise I might not know why we are creating a model in the first place.
3.2 - **Row** doesn’t show as bold
- Image doesn’t show.
- At the end you could have a possible success criteria, so you should now be able to... this makes the reader aware of what we should now know and ensures we have met the criteria

**Comment by shaistilman** [comment]
Thank you Orla i will have a look at all of these now !
