### ISSUE TITLE
Feedback on Tutorial 

### ISSUE THREAD

**Issue by AmeliaYoung** [EdDataScienceEES/tutorial-shaistilman#2]
WELL DONE! This tutorial is amaze, the first thing that stood out to me was the topic- military coups is something I never would have thought of and so interesting!

What went well:
- Very informative README.md, this was very helpful in understanding what to expect from the tutorial- I was learning before I had even begun! 
- Very clear intro, nicely set me up for the tutorial
- I like the section when you list the predictor variables and their names in the dataset
- I found the examples you give so so helpful when you're explaining things- especially in section 3 :) 
- Also the tables you made were so clear in explaining functions and what they do.
- _So what are our key insights?_ sections were very nicely laid out and really helped me consolidate what I was learning.
- I like that you included the section on limitations, this made me feel like I was learning the topic in its entirety, and not just the "good bits".
- Love the topic and level of difficulty of your challenge! 

Points of improvement:
- Maybe add a link in _Prerequisites_ to an article or page with information about interpreting summary outputs, then users can go off and read if they're feeling a bit rusty!
- The images weren't showing for me... most likely my fault but I removed ```{{ site.baseurl }}/``` from the code to get them to show
- In the section _So what is AIC?_ you slightly repeat yourself in lines 98 and 100. Also in this section I think it would be nice to use bold text when referring to variables, just so it's super clear for the user.
- When you first mention stepwise regression in line 212, I think it would be nice to have a quick definition or link here.
- _So what our are next steps_ section: our and are need to be swapped! and I think add a q-mark at the end.

Nailed it!!!!!!

**Comment by shaistilman** [comment]
Thank you !! Ill have a look at all of these <3
